### ISSUE TITLE
The activate script adds a new entry for fermitools everytime it runs

### ISSUE THREAD

**Issue by giacomov** [fermi-lat/ScienceTools-conda-recipe#3]
... even when the entry is already there.

This is done in the `${CONDA_PREFIX}/etc/root/system.rootrc`, in the initial section like:

```Unix.*.Root.DynamicPath:    .:/Users/cr/miniconda2/envs/st_test/lib/root/cint/cint/stl:/Users/cr/miniconda2/envs/st_test/lib/root/cint/cint/include::/Users/cr/miniconda2/envs/st_test/lib/fermitools/:/Users/cr/miniconda2/envs/st_test/lib/fermitools/:/Users/cr/miniconda2/envs/st_test/lib/fermitools/:/Users/cr/miniconda2/envs/st_test/lib/fermitools/:/Users/cr/miniconda2/envs/st_test/lib/fermitools/:/Users/cr/miniconda2/envs/st_test/lib/fermitools/```

The `deactivate` script takes one entry out when run when the user does `source deactivate`, but users rarely do so. If they just close the terminal then the path is not removed. Next time a new shell is opened and a new environment activate, a new entry will be added again. So the number of entries will grow indefinitely.

We need to fix this by making the activate script check whether an entry is there already, and only if it isn't it should insert it.

**Comment by Areustle** [comment]
Which variable do we need to check? $PATH or  "Unix.*.Root.DynamicPath"?

**Comment by Areustle** [comment]
That checks the $PATH. I'm not sure yet about "Unix.*.Root.DynamicPath"
